language: python
python:
  - "2.7"
  - "3.4"
virtualenv:
  system_site_packages: true
before_install:
  - sudo add-apt-repository ppa:cython-dev/master-ppa -y
  - sudo apt-get update -qq
  - sudo apt-get install cython libatlas-dev libatlas3gf-base
install:
  - pip install numpy
  - python setup.py build_ext --inplace
script:
  - python -m timeit -s "import Fibo" "Fibo.fib(30)"
  - python -m timeit -s "import cyFibo" "cyFibo.fib(30)"
  - python -m timeit -s "import cyFibo" "cyFibo.fib_int(30)"
  - python -m timeit -s "import cyFibo" "cyFibo.fib_cdef(30)"
  - python -m timeit -s "import cyFibo" "cyFibo.fib_cpdef(30)"
  - python -m timeit -s "import cyFibo" "cyFibo.fib_int_cpdef(30)"
  - python -m timeit -s "import Fibo" "Fibo.fib_cached(30)"
  - python -m timeit -s "import cyStdDev; import numpy as np; a = np.arange(1e6)" "cyStdDev.cStdDev(a)"
  - python FiboTimeit.py
