language: python
python:
  - "2.7"
  - "3.4"
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install libatlas-dev libatlas3gf-base
install:
  - pip install numpy
  - pip install cython
  - cd src
  - python setup.py build_ext --inplace
script:
  - python -m timeit -s "import Fibo" "Fibo.fib(30)"
  - python -m timeit -s "import cyFibo" "cyFibo.fib(30)"
  - python -m timeit -s "import cyFibo" "cyFibo.fib_int(30)"
  - python -m timeit -s "import cyFibo" "cyFibo.fib_cdef(30)"
  - python -m timeit -s "import cyFibo" "cyFibo.fib_cpdef(30)"
  - python -m timeit -s "import cyFibo" "cyFibo.fib_int_cpdef(30)"
  - python -m timeit -s "import cFibo" "cFibo.fib(30)"
  - python -m timeit -s "import Fibo" "Fibo.fib_cached(30)"
  - python -m timeit -s "import cyStdDev; import numpy as np; a = np.arange(1e6)" "cyStdDev.cStdDev(a)"
  - python FiboTimeit.py
